"""
timingtask.rl — reinforcement learning on the timing task.
=======================================================================

The network is never told when to lick. It emits a per-step lick probability,
acts, and learns only from reward. Following Song, Yang & Wang 2017 (eLife
6:e21492): a recurrent policy, REINFORCE with a LEARNED VALUE BASELINE, and no
shaping beyond what the task itself provides.

WHY A PER-STEP BERNOULLI IS ALSO A RAMP-TO-BOUND
------------------------------------------------
Policy gradient needs a stochastic policy; the timing literature wants a ramp
crossed against a threshold. These are the same object. The policy emits a
logit z(t); P(lick at t) = sigmoid(z(t)) is a HAZARD RATE, and the realised lick
time is the first passage of that hazard. A rising z is a ramp, the sigmoid's
midpoint is the threshold, and the lick-time distribution is generated by the
dynamics rather than parameterised -- which is the point. Nothing prescribes t*.

EPISODE = ONE TRIAL
-------------------
Cross-trial information reaches the policy through the previous-trial
observation channels, held constant for the whole trial, so the recurrent state
does not have to bridge trials. BPTT is then ~150 steps rather than thousands.
The generator's own state (the delay schedule, the outcome history, the history
ring) still persists across episodes -- only the network's hidden state resets.

THE FAILURE MODE TO WATCH
-------------------------
Song et al.'s networks can settle into never acting, because their reward for
correct withholding is exactly 0. That does NOT apply unchanged here: this task
charges ``time_penalty`` every step, so waiting is strictly expensive. Track ``p_engaged`` and
``p_correct`` separately anyway -- a single accuracy number cannot tell an agent
that times well from one that does nothing.
"""
from __future__ import annotations

import math
from typing import Any, Callable, Dict, List, Optional

import numpy as np
import torch
import torch.nn as nn
from torch import Tensor
from torch.distributions import Categorical

from .config import ObservationConfig, SchedulerConfig, TimingTaskConfig, make_config
from .generator import TrialGenerator
from .monitor import Monitor, MonitorList
from .scheduler import DelayScheduler

__all__ = ["ActorCritic", "RLTrainer", "rollout", "attach_states", "summarise",
           "summarise_by_delay", "format_delay_report"]

WAIT, LICK = 0, 1


class ActorCritic(nn.Module):
    """A recurrent core with a policy head and a value head.

    The core is any model from :mod:`timingtask.models` -- its ``step``
    stays a pure function of ``(x, h)``, so ``torch.func`` can still take
    Jacobians of the dynamics and the geometry tools apply unchanged to ``h``.
    Only the heads are new.
    """

    def __init__(self, core: nn.Module, hidden_size: Optional[int] = None,
                 n_actions: int = 2):
        super().__init__()
        self.core = core
        h = int(hidden_size or getattr(core, "hidden_size"))
        self.policy = nn.Linear(h, n_actions)
        self.value = nn.Linear(h, 1)
        with torch.no_grad():
            # Start near-indifferent. A large initial bias either way sends the
            # agent straight into a lick-always or never-lick policy, and the
            # gradient out of either is weak.
            self.policy.weight.mul_(0.1)
            self.policy.bias.zero_()

    def init_state(self, batch_size: int, device=None) -> Tensor:
        return self.core.init_state(batch_size, device)

    def step(self, x: Tensor, h: Tensor):
        """One step. Returns ``(h, logits, value)``."""
        h = self.core.step(x, h)
        return h, self.policy(h), self.value(h).squeeze(-1)


def rollout(model: ActorCritic, gens: List[TrialGenerator], *,
            greedy: bool = False, max_steps: int = 4000, device: str = "cpu",
            min_action_prob: float = 0.0):
    """Run one episode (= one trial) in each of ``gens``, in lockstep.

    Generators run in parallel purely for batching; each keeps its own delay
    schedule, outcome history and trial history, so they are independent
    animals.

    ``min_action_prob`` (eps) mixes the policy with a uniform distribution,
    p <- eps + (1 - 2 eps) p, before sampling. This is a HARD floor on the
    lick probability, and therefore on the entropy: H >= H(eps). The entropy
    bonus in the loss cannot do this -- its restoring force decays as
    |Delta| exp(-|Delta|), so it vanishes exactly when the policy has become
    confident and a floor is needed. The mixed distribution is the one that
    acts and the one whose log-probability is scored, so the policy gradient
    stays correct rather than being taken with respect to a policy that was
    not followed.
    """
    B = len(gens)
    eps = float(min_action_prob)
    h = model.init_state(B, device)
    h_init = h
    obs = torch.tensor(np.stack([g.observe() for g in gens]), dtype=torch.float32,
                       device=device)
    done = np.zeros(B, bool)
    logps, values, rewards, ents, masks, hs, logits_all, itis, posts = \
        [], [], [], [], [], [], [], [], []
    # The drive the network actually saw, step by step. Kept so a trial can
    # be exported WITH its inputs: the pullback metric of the dynamics is
    # taken with respect to (x, h), and h alone does not determine x.
    obs_all = []
    records: List[Optional[Dict[str, Any]]] = [None] * B

    for _ in range(max_steps):
        obs_all.append(obs)
        h, logits, v = model.step(obs, h)
        if eps > 0:
            probs = torch.softmax(logits, dim=-1)
            n_act = probs.shape[-1]
            dist = Categorical(probs=eps + (1.0 - n_act * eps) * probs)
        else:
            dist = Categorical(logits=logits)
        a = logits.argmax(-1) if greedy else dist.sample()
        logps.append(dist.log_prob(a))
        ents.append(dist.entropy())
        values.append(v)
        hs.append(h)
        logits_all.append(logits)

        r = np.zeros(B, np.float32)
        nxt = np.zeros((B, gens[0].obs_size), np.float32)
        in_iti = np.zeros(B, np.float32)
        in_post = np.zeros(B, np.float32)
        for i, g in enumerate(gens):
            if done[i]:
                nxt[i] = obs[i].detach().cpu().numpy()
                continue
            in_iti[i] = float(g.phase == "iti")     # phase BEFORE the step
            in_post[i] = float(g.phase == "post")
            res = g.step(bool(a[i].item()))
            r[i], nxt[i] = res.reward, res.obs
            if res.record is not None:
                records[i] = res.record
                done[i] = True
        rewards.append(torch.tensor(r, device=device))
        itis.append(torch.tensor(in_iti, device=device))
        posts.append(torch.tensor(in_post, device=device))
        masks.append(torch.tensor(~done, dtype=torch.float32, device=device))
        obs = torch.tensor(nxt, dtype=torch.float32, device=device)
        if done.all():
            break

    # mask[t] is 1 while the trial was still running at step t
    m = torch.stack([torch.ones_like(masks[0])] + masks[:-1])
    return {"logp": torch.stack(logps), "value": torch.stack(values),
            "reward": torch.stack(rewards), "entropy": torch.stack(ents),
            "mask": m, "hidden": torch.stack(hs), "logits": torch.stack(logits_all),
            "h_init": h_init, "iti": torch.stack(itis),
            "obs": torch.stack(obs_all),
            "post": torch.stack(posts), "records": records}




def attach_states(out: Dict[str, Any]) -> None:
    """Attach the per-trial time series to each record in ``out["records"]``.

    Every series is truncated at that trial's own length, so padding from
    after the trial ended can never reach a plot or an export.

        readout  (T,)      the lick-minus-wait logit gap, which IS the policy
        value    (T,)      the critic
        hidden   (T, N)    the recurrent state
        obs      (T, n_in) the drive the network was given

    This was written out three times, and two of the three copies quietly
    omitted ``hidden`` -- so ``collect_states=True`` returned no states at all
    from ``switching_test`` and ``probe``, and only ``evaluate`` could feed an
    export. A new rollout path should call this rather than copy it again.
    """
    d = (out["logits"][..., LICK] - out["logits"][..., WAIT]).cpu().numpy()
    vv = out["value"].cpu().numpy()
    hh = out["hidden"].cpu().numpy()
    oo = out["obs"].cpu().numpy()
    for i, r in enumerate(out["records"]):
        if r is None:
            continue
        T = int(r["trial_steps"])
        r["readout"] = d[:T, i].astype(np.float32)
        r["value"] = vv[:T, i].astype(np.float32)
        r["hidden"] = hh[:T, i].astype(np.float32)
        r["obs"] = oo[:T, i].astype(np.float32)

class RLTrainer:
    """REINFORCE with a learned value baseline.

    Parameters
    ----------
    gamma : discount. 1.0 optimises the true undiscounted trial return, which is
        what the task's own economics express; < 1 shortens the credit horizon
        and can help early on.
    min_action_prob : eps, the floor under every action probability. This is the
        exploration mechanism. It is a floor and not a bonus for a specific
        reason: the policy gradient's own score function is
        d log pi(lick)/d Delta = 1 - p, so a policy that has become certain has
        almost no gradient however bad the outcome, and any term whose force
        also carries a p(1-p) factor -- an entropy bonus does -- dies at exactly
        the same moment. A floor instead keeps the disfavoured action sampled
        with probability at least eps, and the score for that sampled action is
        ~ p(1-p)/eps, which stays usable. See docs/timing_entropy_note.md.
    """

    def __init__(self,
                 task_config: Optional[TimingTaskConfig] = None,
                 scheduler_config: Optional[SchedulerConfig] = None,
                 obs_config: Optional[ObservationConfig] = None,
                 *,
                 variant: Optional[str] = None,
                 n_envs: int = 16,
                 lr: float = 4e-3,
                 gamma: float = 1.0,
                 value_coef: float = 0.5,
                 grad_clip: float = 1.0,
                 reward_scale: float = 0.1,
                 iti_readout_penalty: float = 0.0,
                 activity_penalty: float = 0.0,
                 activity_deriv_penalty: float = 0.0,
                 activity_scope: str = "iti",
                 min_action_prob: float = 0.0,
                 seed: int = 0):
        if variant is not None:
            task_config, scheduler_config = make_config(variant)
        self.cfg = task_config or TimingTaskConfig()
        self.scheduler_cfg = scheduler_config or SchedulerConfig()
        self.obs_cfg = obs_config or ObservationConfig()
        self.n_envs = int(n_envs)
        self.lr, self.gamma = float(lr), float(gamma)
        self.value_coef = float(value_coef)
        self.grad_clip = float(grad_clip)
        # Rewards here are large (reward 15, per-step costs). Advantages
        # of that magnitude make the policy gradient explode; scale once, here,
        # rather than retuning lr for every reward change.
        self.reward_scale = float(reward_scale)
        # Penalty on P(lick) during the ITI, applied EVERY ITI step whether or
        # not a lick happened. The per-lick penalty only fires once the agent
        # has already licked; this one shapes the readout directly, so "keep
        # the lick drive low until the cue" has a gradient at every step.
        self.iti_readout_penalty = float(iti_readout_penalty)
        # Penalties on the hidden state. Unlike the readout penalty these are
        # DIFFERENTIABLE terms added to the loss, not shaped rewards. Routing
        # them through the return would be close to useless: activity is not an
        # action, so the credit-assignment path from "the state was large" to
        # "which action caused it" is exactly the one REINFORCE is worst at. As
        # loss terms they act on W_rec and W_in directly. The cost is that they
        # are a regulariser on the network, not something the animal
        # experiences -- they change the model, not the task.
        #
        #   activity:  mean ||h_t||^2 / N
        #   deriv:     mean ||h_t - h_{t-1}||^2 / N
        #
        # activity_scope selects the steps they are averaged over:
        #   "iti"  -- stop-licking period only. Leaves the cue-evoked response
        #             untouched, so quieting the baseline and responding to the
        #             cue are two independent knobs rather than one.
        #   "full" -- every live step: a metabolic budget on the whole trial.
        #             Biologically the more defensible constraint, but it also
        #             prices the cue response, so the coefficient matters more.
        self.activity_penalty = float(activity_penalty)
        self.activity_deriv_penalty = float(activity_deriv_penalty)
        if activity_scope not in ("iti", "full"):
            raise ValueError(f"activity_scope must be 'iti' or 'full', "
                             f"got {activity_scope!r}")
        self.activity_scope = str(activity_scope)
        # Hard floor on every action probability; see rollout().
        self.min_action_prob = float(min_action_prob)

        rngs = [np.random.default_rng(seed * 1000 + i) for i in range(self.n_envs)]
        self.gens = [TrialGenerator(self.cfg,
                                    DelayScheduler(self.scheduler_cfg, r),
                                    self.obs_cfg, r) for r in rngs]

    @property
    def obs_size(self) -> int:
        return self.gens[0].obs_size

    def _returns(self, reward: Tensor, mask: Tensor) -> Tensor:
        T, B = reward.shape
        out = torch.zeros_like(reward)
        run = torch.zeros(B, device=reward.device)
        for t in range(T - 1, -1, -1):
            run = reward[t] + self.gamma * run * mask[t]
            out[t] = run
        return out

    def train(self, model: ActorCritic, *, steps: int = 2000,
              log_every: int = 100, monitors: Optional[Monitor] = None,
              on_log: Optional[Callable[[int, Dict], None]] = None,
              keep_records: bool = True,
              target_delay: Optional[float] = None,
              patience: Optional[int] = None, min_delta: float = 0.01,
              sched: Optional[Dict[str, Any]] = None,
              phase: str = "curriculum", reset: bool = True,
              score: str = "delay+correct",
              verbose: bool = True) -> Dict[str, List[float]]:
        """Train, and (by default) keep every trial record in ``self.records``.

        The records are what the behavioural plots are made from. 400 updates
        x 16 environments is ~6400 dicts, which is small; without them the only
        trace of a run is the log line, and a log line cannot show a raster.

        Two ways to stop before ``steps``:

        ``target_delay`` -- stop once the batch-mean required delay reaches it.
        The point of the run is to get the delay up; there is nothing to learn
        from grinding on after it has.

        ``patience`` -- stop after this many LOG POINTS with no improvement
        greater than ``min_delta`` in the best score seen so far. The score is
        the batch-mean delay plus the rewarded fraction, so a run that neither
        advances the curriculum nor gets more accurate counts as stalled. A run
        that is oscillating without progressing -- which is what 650 updates of
        the 1500-step `act` run were -- exits instead of burning the budget.

        Training in PHASES
        ------------------
        ``sched`` switches the delay schedule PERMANENTLY (unlike ``test``,
        which restores it), and ``reset=False`` keeps the records, the weight
        snapshots and the Adam state from the previous call. Together they let
        one agent be trained through several schedules back to back -- the
        growing curriculum, then a held long delay, then a switching one --
        which is the only way it can ever be asked to infer the delay rather
        than memorise the one the curriculum left it on. Each record carries
        ``phase`` so the three can be separated afterwards.

        ``score`` selects what ``patience`` watches. ``delay+correct`` is right
        while the curriculum is growing the delay. Once the delay is fixed or
        switching there is no delay to grow and its batch-to-batch scatter is
        pure noise, so use ``correct``.
        """
        if sched:
            for k, v in sched.items():
                setattr(self.scheduler_cfg, k, v)
            for g in self.gens:
                g.scheduler.reset()
                # The current trial read its delay before the schedule changed;
                # restart it so no trial straddles two phases.
                g._start_trial()
        if reset or not hasattr(self, "records"):
            self.records: List[Dict[str, Any]] = []
            self.weight_snapshots: List[Dict[str, Any]] = []
            self.opt = torch.optim.Adam(model.parameters(), lr=self.lr)
        mons = monitors if isinstance(monitors, MonitorList) else \
            MonitorList([monitors] if monitors is not None else [])
        opt = self.opt
        # Snapshots of the two readout vectors at each log point. Weights change
        # once per UPDATE (one gradient step over a batch of 16 trials), never
        # within a trial -- inside a trial the network is a fixed dynamical
        # system and only its state moves. So the resolution here is updates.
        prev = {n: p.detach().clone() for n, p in model.named_parameters()}
        hist: Dict[str, List[float]] = {
            "step": [], "return": [], "p_engaged": [], "p_correct": [],
            "p_early": [], "entropy": [], "policy_loss": [], "value_loss": []}

        best_score, stale, self.stop_reason = -float("inf"), 0, "steps"
        for i in range(1, steps + 1):
            out = rollout(model, self.gens,
                          min_action_prob=self.min_action_prob)
            # Two masks, and the difference matters.
            #   m_data : the trial is still running. Used for the RETURN, so a
            #            reward earned anywhere in the trial still lands.
            #   m      : the trial is still running AND the action still has a
            #            consequence. The post-lick wind-down fails the second
            #            test: it exists only so the recorded data contains a
            #            peri-lick epoch, and nothing done there changes any
            #            outcome. Training the policy on 75 steps of
            #            consequence-free actions per trial is fitting noise,
            #            so every loss term uses m, not m_data.
            m_data = out["mask"]
            m = m_data * (1.0 - out["post"])
            rew = out["reward"] * self.reward_scale
            if self.iti_readout_penalty:
                p_lick = torch.softmax(out["logits"], dim=-1)[..., LICK]
                rew = rew - self.iti_readout_penalty * p_lick.detach() * out["iti"]
            R = self._returns(rew, m_data)
            adv = (R - out["value"]).detach()
            # Normalise the advantage over live steps only; padding after a
            # trial ends would otherwise drag the mean.
            live = m.sum().clamp_min(1)      # loss-eligible steps, POST excluded
            mu = (adv * m).sum() / live
            sd = (((adv - mu) ** 2 * m).sum() / live).sqrt().clamp_min(1e-6)
            adv = (adv - mu) / sd

            policy_loss = -((out["logp"] * adv) * m).sum() / live
            value_loss = (((out["value"] - R) ** 2) * m).sum() / live
            # Entropy is MEASURED, not optimised. It is the clearest single
            # readout of how deterministic the policy has become -- and the
            # thing that keeps it from becoming useless is the probability
            # floor in rollout(), not a term here.
            entropy = (out["entropy"] * m).sum() / live
            loss = policy_loss + self.value_coef * value_loss

            act_pen = dact_pen = None
            if self.activity_penalty or self.activity_deriv_penalty:
                H_ = out["hidden"]                       # (T, B, N)
                w = m if self.activity_scope == "full" else m * out["iti"]
                n_w = w.sum().clamp_min(1)
                if self.activity_penalty:
                    act_pen = ((H_ ** 2).mean(-1) * w).sum() / n_w
                    loss = loss + self.activity_penalty * act_pen
                if self.activity_deriv_penalty:
                    # NOT `prev`: that name holds the previous-update weight
                    # snapshot used by the diagnostics below, and rebinding it
                    # to a tensor made every dact_* variant crash at the first
                    # log point.
                    h_prev = torch.cat([out["h_init"].unsqueeze(0), H_[:-1]], 0)
                    dact_pen = (((H_ - h_prev) ** 2).mean(-1) * w).sum() / n_w
                    loss = loss + self.activity_deriv_penalty * dact_pen

            opt.zero_grad()
            loss.backward()
            # Returns the total norm BEFORE clipping, which is the diagnostic:
            # a run pinned at grad_clip is being throttled every update and the
            # effective learning rate is no longer the one that was set.
            gnorm = float(nn.utils.clip_grad_norm_(
                model.parameters(),
                self.grad_clip if self.grad_clip else float("inf")))
            opt.step()

            recs = [r for r in out["records"] if r is not None]
            for r in recs:
                mons.on_trial(r)
            if keep_records:
                for _r in recs:
                    _r["phase"] = phase
                self.records.extend(recs)

            if i % log_every == 0 or i == 1:
                s = summarise(recs)
                hist["step"].append(i)
                hist["return"].append(
                    float((out["reward"] * m_data).sum() / len(self.gens)))
                with torch.no_grad():
                    pl = torch.softmax(out["logits"], -1)[..., LICK]
                    hist.setdefault("p_lick_iti", []).append(float(
                        (pl * out["iti"] * m).sum()
                        / (out["iti"] * m).sum().clamp_min(1)))
                for k in ("p_engaged", "p_correct", "p_early",
                          "p_iti_lick", "n_iti_licks", "p_cue_success",
                          "delay", "first_lick", "p_miss",
                          "value_gain", "reward_rate"):
                    hist.setdefault(k, []).append(s[k])
                hist["entropy"].append(float(entropy.detach()))
                if act_pen is not None:
                    hist.setdefault("act_pen", []).append(float(act_pen.detach()))
                if dact_pen is not None:
                    hist.setdefault("dact_pen", []).append(float(dact_pen.detach()))
                hist.setdefault("grad_norm", []).append(gnorm)
                with torch.no_grad():
                    W = model.policy.weight
                    w_delta = (W[LICK] - W[WAIT]).detach().clone()
                    w_v = model.value.weight[0].detach().clone()
                    # ||w_delta|| is the GAIN of the policy readout: the logit
                    # gap is w_delta . h, so this bounds how confident the
                    # policy can become for a state of a given size.
                    hist.setdefault("w_delta_norm", []).append(float(w_delta.norm()))
                    hist.setdefault("w_value_norm", []).append(float(w_v.norm()))
                    hist.setdefault("W_rec_norm", []).append(
                        float(model.core.rec.weight.norm()))
                    hist.setdefault("W_in_norm", []).append(
                        float(model.core.inp.weight.norm()))
                    # Relative size of the last step, per parameter block. A run
                    # that has stopped moving has this at ~0; one still being
                    # thrown around does not.
                    # Only blocks that actually receive a gradient: h0 is frozen
                    # at zero and core.out is the SUPERVISED readout, which the
                    # actor-critic never calls. Both would otherwise plot a
                    # meaningless ratio -- a norm of zero in the denominator.
                    for n, p in model.named_parameters():
                        n0 = float(prev[n].norm())
                        if p.grad is not None:
                            # NaN, not skip: every series must stay the same
                            # length as `step` or the plot silently shifts it.
                            hist.setdefault(f"d_{n}", []).append(
                                float((p.detach() - prev[n]).norm() / n0)
                                if n0 >= 1e-8 else float("nan"))
                        prev[n] = p.detach().clone()   # always, or a block that
                        # started at zero would be skipped for ever
                    self.weight_snapshots.append(
                        {"step": i, "w_delta": w_delta.cpu().numpy(),
                         "w_value": w_v.cpu().numpy(),
                         "b_delta": float(model.policy.bias[LICK]
                                          - model.policy.bias[WAIT])})
                hist.setdefault("trials", []).append(len(self.records))
                hist["policy_loss"].append(float(policy_loss.detach()))
                hist["value_loss"].append(float(value_loss.detach()))
                if verbose:
                    print(f"    {i:5d}/{steps}  return {hist['return'][-1]:8.2f}  "
                          f"engaged {s['p_engaged']:.2f}  correct {s['p_correct']:.2f}  "
                          f"early {s['p_early']:.2f}  H {float(entropy):.3f}  "
                          f"delay {s['delay']:.2f}", flush=True)
                if on_log:
                    on_log(i, {**s, "entropy": float(entropy.detach()),
                               "return": hist["return"][-1]})

                # --- stopping rules, evaluated only at log points
                mean_delay = float(np.nanmean([r["delay"] for r in recs])
                                   if recs else float("nan"))
                if target_delay is not None and mean_delay >= target_delay:
                    self.stop_reason = f"target_delay {target_delay:g} reached"
                    break
                if patience:
                    sc = (s["p_correct"] if score == "correct"
                          else mean_delay + s["p_correct"])
                    if sc > best_score + min_delta:
                        best_score, stale = sc, 0
                    else:
                        stale += 1
                        if stale >= patience:
                            self.stop_reason = (
                                f"stalled: no gain > {min_delta:g} in "
                                f"{patience} log points")
                            break
        mons.close()
        if verbose or self.stop_reason != "steps":
            print(f"    stopped at update {i}/{steps}: {self.stop_reason}",
                  flush=True)
        return hist


    def evaluate(self, model: ActorCritic, *, n_trials: int = 400,
                 greedy: bool = False, freeze_scheduler: bool = True,
                 max_steps: int = 4000, collect_states: bool = False
                 ) -> List[Dict[str, Any]]:
        """Run the trained model without learning and return trial records.

        ``freeze_scheduler`` holds the required delay where training left it,
        so the resulting raster is the behaviour at one delay rather than a
        curriculum still in motion. ``greedy`` takes the most likely action
        instead of sampling, which removes the policy's own stochasticity --
        useful to see the deterministic ramp, misleading as a picture of
        behaviour, so it is off by default.
        """
        was_training = model.training
        model.eval()                     # also switches off the network noise
        if freeze_scheduler:
            for g in self.gens:
                g.scheduler.frozen = True
        recs: List[Dict[str, Any]] = []
        try:
            with torch.no_grad():
                while len(recs) < n_trials:
                    out = rollout(model, self.gens, greedy=greedy,
                                  max_steps=max_steps,
                                  min_action_prob=self.min_action_prob)
                    batch = [r for r in out["records"] if r is not None]
                    if collect_states:
                        attach_states(out)
                    recs += batch
        finally:
            if freeze_scheduler:
                for g in self.gens:
                    g.scheduler.frozen = False
            model.train(was_training)
        return recs[:n_trials]


    def _sched_snapshot(self):
        """Mutable scheduler state per environment, minus the shared config and
        the RNG. Lets a test condition reset the schedulers and put them back."""
        import copy
        return [{k: copy.deepcopy(v) for k, v in g.scheduler.__dict__.items()
                 if k not in ("config", "rng")} for g in self.gens]

    def _sched_restore(self, snaps):
        for g, s in zip(self.gens, snaps):
            g.scheduler.__dict__.update(s)

    def test(self, model: ActorCritic, *, n_trials: int = 10000,
             sched: Optional[Dict[str, Any]] = None,
             collect_states: bool = False, max_steps: int = 4000
             ) -> List[Dict[str, Any]]:
        """Run the trained agent, weights frozen, under a DIFFERENT schedule.

        The two conditions worth running are a long fixed delay and a switching
        one. Both ask the same thing: the agent was trained at delays it grew
        into gradually -- put it at a delay it has to hold, or one that changes
        under it, and see whether the lick time follows. Testing at the delay
        training happened to end on cannot distinguish an agent that times from
        one that memorised an interval, which is why it is not run any more.
        """
        was_training = model.training
        model.eval()
        snaps = self._sched_snapshot()
        cfg_backup = {k: getattr(self.scheduler_cfg, k) for k in (sched or {})}
        recs: List[Dict[str, Any]] = []
        try:
            for k, v in (sched or {}).items():
                setattr(self.scheduler_cfg, k, v)
            for g in self.gens:                 # re-derive mode-specific state
                g.scheduler.reset()
                # The generator read its delay when the current trial STARTED,
                # which was before the schedule changed. Restart it, or the
                # first trial of every environment silently runs at the old
                # delay and lands in the records as if it were a test trial.
                g._start_trial()
            with torch.no_grad():
                while len(recs) < n_trials:
                    out = rollout(model, self.gens, max_steps=max_steps,
                                  min_action_prob=self.min_action_prob)
                    if collect_states:
                        attach_states(out)
                    recs += [r for r in out["records"] if r is not None]
        finally:
            for k, v in cfg_backup.items():
                setattr(self.scheduler_cfg, k, v)
            self._sched_restore(snaps)
            model.train(was_training)
        return recs[:n_trials]

    def probe(self, model: ActorCritic, *, n_trials: int = 2000,
              max_delay: float = 1.8, collect_states: bool = False,
              promote: bool = True, sched: Optional[Dict[str, Any]] = None,
              max_steps: int = 4000) -> List[Dict[str, Any]]:
        """Run the trained agent with the CURRICULUM STILL ACTIVE but the
        weights frozen.

        A fixed-delay evaluation cannot answer the question that matters: the
        agent has one delay it licks at, so holding the delay fixed only shows
        whether that one number is right. Here the scheduler keeps promoting
        exactly as it did in training, up to ``max_delay``, while nothing
        learns. If the agent can follow the growing delay, it is timing from
        the trial's own evidence; if its lick time stays put while the delay
        rises past it, it had memorised one interval.
        """
        was_training = model.training
        model.eval()
        old_max = self.scheduler_cfg.max_delay
        self.scheduler_cfg.max_delay = float(max_delay)
        # After PHASED training the live schedule is whatever the last phase
        # left behind -- switching blocks, say -- and a probe run under that
        # is not a probe at all. `sched` puts a growing curriculum back for the
        # duration, and it is restored afterwards like any test condition.
        snaps = self._sched_snapshot() if sched else None
        cfg_backup = ({k: getattr(self.scheduler_cfg, k) for k in sched}
                      if sched else {})
        if sched:
            for k, v in sched.items():
                setattr(self.scheduler_cfg, k, v)
            for g in self.gens:
                g.scheduler.reset()
                g._start_trial()
        # If training stopped while still in cue association the delay cannot
        # grow, and the probe would answer nothing. Advancing the stage here
        # asks the question directly: can an agent trained ONLY on the cue
        # follow a growing delay, with no further weight change?
        stages = [g.scheduler.training_stage for g in self.gens]
        if promote:
            for g in self.gens:
                if g.scheduler.training_stage == "cue_association":
                    g.scheduler.training_stage = "autolearn"
        recs: List[Dict[str, Any]] = []
        try:
            with torch.no_grad():
                while len(recs) < n_trials:
                    out = rollout(model, self.gens, max_steps=max_steps,
                                  min_action_prob=self.min_action_prob)
                    if collect_states:
                        attach_states(out)
                    recs += [r for r in out["records"] if r is not None]
        finally:
            self.scheduler_cfg.max_delay = old_max
            for k, v in cfg_backup.items():
                setattr(self.scheduler_cfg, k, v)
            if snaps is not None:
                self._sched_restore(snaps)
            else:
                for g, st in zip(self.gens, stages):
                    g.scheduler.training_stage = st
            model.train(was_training)
        return recs[:n_trials]



# --------------------------------------------------------------------------- #
# Behaviour split by the required delay -- the only way to ask whether the
# agent TIMES rather than emitting one memorised interval.
# --------------------------------------------------------------------------- #
def summarise_by_delay(records: List[Dict[str, Any]], *,
                       max_rows: int = 8) -> Dict[str, Any]:
    """Split trials by required delay and report a CENSORING-SAFE lick time.

    The plain mean first-lick time is not comparable across delays. A trial
    ends at ``delay + answer_window``, so a longer delay simply leaves more
    room for a late lick to be recorded, and an agent whose lick time never
    moves still shows a later mean at the longer delay. In round 6 this
    manufactured an apparent 0.19 s shift in an agent that was, within the
    window both conditions shared, emitting exactly the same interval.

    ``first_lick_cut`` therefore averages only licks earlier than ``cut``, the
    deadline of the SHORTEST trial in the set -- a time every condition had an
    equal opportunity to produce. ``tracking`` is the slope of that quantity
    against the delay: 1.0 is perfect timing, 0.0 is a fixed interval.
    """
    cued = [r for r in records if not r.get("no_cue_trial")]
    if not cued:
        return dict(cut=float("nan"), rows=[], tracking=float("nan"))
    cut = min(float(r["delay"]) + float(r.get("answer_window", 0.0))
              for r in cued)
    delays = sorted({round(float(r["delay"]), 2) for r in cued})
    # A curriculum sweeps a continuum of delays; bin it so the table stays
    # readable. Discrete test conditions (one or two delays) are left alone.
    width = 0.0
    if len(delays) > max_rows:
        width = (delays[-1] - delays[0]) / max_rows or 0.1
    groups: Dict[float, list] = {}
    for r in cued:
        d = float(r["delay"])
        key = (round(delays[0] + width * int((d - delays[0]) / width), 2)
               if width else round(d, 2))
        groups.setdefault(key, []).append(r)
    rows = []
    for d in sorted(groups):
        g = groups[d]
        fl = np.array([r["first_lick_s"] for r in g
                       if r.get("first_lick_s") is not None], float)
        sub = fl[fl < cut]
        rows.append(dict(
            delay=d, n=len(g), p_lick=len(fl) / len(g),
            first_lick=float(fl.mean()) if len(fl) else float("nan"),
            first_lick_cut=float(sub.mean()) if len(sub) else float("nan"),
            n_cut=int(len(sub)),
            p_correct=float(np.mean([bool(r.get("rewarded")) for r in g])),
            p_early=float(np.mean([bool(r.get("early")) for r in g]))))
    tracking = float("nan")
    good = [r for r in rows if r["n_cut"] >= 20]
    if len(good) > 1:
        x = np.array([r["delay"] for r in good], float)
        y = np.array([r["first_lick_cut"] for r in good], float)
        if x.std() > 0:
            tracking = float(np.polyfit(x, y, 1)[0])
    return dict(cut=cut, rows=rows, tracking=tracking, binned=bool(width))


def format_delay_report(rep: Dict[str, Any], label: str = "",
                        indent: str = "    ") -> str:
    """The table `summarise_by_delay` produces, as text for a training log."""
    if not rep["rows"]:
        return f"{indent}{label}: no cued trials"
    L = [f"{indent}{label} by delay "
         f"(first lick capped at {rep['cut']:.2f}s -- the shortest trial's "
         f"deadline, so the columns are comparable"
         + ("; delays binned)" if rep.get("binned") else ")"),
         f"{indent}  {'delay':>6s} {'n':>6s} {'p(lick)':>8s} {'FL':>7s} "
         f"{'FL_cut':>7s} {'n_cut':>6s} {'corr':>6s} {'early':>6s}"]
    for r in rep["rows"]:
        L.append(f"{indent}  {r['delay']:6.2f} {r['n']:6d} {r['p_lick']:8.2f} "
                 f"{r['first_lick']:7.3f} {r['first_lick_cut']:7.3f} "
                 f"{r['n_cut']:6d} {r['p_correct']:6.2f} {r['p_early']:6.2f}")
    L.append(f"{indent}  tracking slope d(FL_cut)/d(delay) = "
             f"{rep['tracking']:+.3f}   (1 = times the delay, 0 = fixed "
             f"interval)")
    return "\n".join(L)

def summarise(records: List[Dict[str, Any]]) -> Dict[str, float]:
    """Behavioural summary of a batch of trials.

    ``p_engaged`` and ``p_correct`` are reported separately on purpose: an agent
    that never licks scores no errors, and a single accuracy number cannot see
    the difference between good timing and doing nothing.
    """
    cued = [r for r in records if not r.get("no_cue_trial")]
    if not cued:
        return dict(p_engaged=0., p_correct=0., p_early=0., p_miss=0.,
                    p_iti_lick=float("nan"), n_iti_licks=float("nan"),
                    p_cue_success=float("nan"),
                    delay=float("nan"), value_gain=float("nan"),
                    reward_rate=float("nan"),
                    first_lick=float("nan"), n=0)
    licked = [r for r in cued if r.get("decisive_lick_s") is not None]
    rew = [r for r in cued if r.get("rewarded")]
    fl = [r["first_lick_s"] for r in cued if r.get("first_lick_s") is not None]
    return dict(
        p_engaged=len(licked) / len(cued),
        p_correct=len(rew) / max(len(licked), 1),
        p_early=sum(bool(r.get("early")) for r in cued) / len(cued),
        p_miss=sum(bool(r.get("miss")) for r in cued) / len(cued),
        # ITI licking over ALL trials, including no-cue catch trials: the
        # stop-licking period is the same on both, so restricting to cued
        # trials would drop a tenth of the evidence for no reason.
        p_iti_lick=sum(bool(r.get("iti_licked")) for r in records) / len(records),
        n_iti_licks=float(np.mean([r.get("n_iti_licks", 0) for r in records])),
        # Matches the scheduler's definition: an early lick is not a cue
        # response even if it fell inside the response window, so the number
        # reported here is the same number promotion is judged on.
        p_cue_success=(sum(bool(r.get("cue_success")) and not r.get("early")
                           for r in cued) / len(cued)),
        delay=float(np.mean([r["delay"] for r in cued])),
        value_gain=float(np.mean([r.get("value_gain", 1.0) for r in cued])),
        reward_rate=float(np.mean([r.get("reward_rate", float("nan"))
                                   for r in cued])),
        first_lick=float(np.mean(fl)) if fl else float("nan"),
        n=len(cued))
