"""
timingtask.rl: reinforcement learning on the timing task.

The agent is a recurrent network with a policy head and a value head. At each
step it emits a lick probability, acts, and receives the reward defined by the
task. Training follows Song, Yang and Wang (2017): REINFORCE with a learned
value baseline, and no target lick time anywhere in the objective.

Policy
------
The policy produces two logits per step. With ``P(lick at t) = sigmoid(z_lick -
z_wait)`` the per-step lick probability is a discrete-time hazard, and the
lick time is its first passage. A rising logit gap is therefore equivalent to
a ramp crossing a threshold, with the lick-time distribution generated by the
network dynamics rather than parameterised.

Episodes
--------
One episode is one trial. Information about previous trials reaches the policy
through the previous-trial observation channels, which are held constant for
the whole trial, so the hidden state is reset at every trial boundary and
backpropagation through time spans a single trial. The generator's own state
(delay schedule, outcome history, history channels) persists across episodes.

Diagnostics
-----------
``p_engaged`` (fraction of cued trials with a lick) and ``p_correct``
(fraction of licked trials that were rewarded) are reported separately, since
a policy that never licks makes no errors.
"""
from __future__ import annotations

import math
from typing import Any, Callable, Dict, List, Optional

import numpy as np
import torch
import torch.nn as nn
from torch import Tensor
from torch.distributions import Categorical

from .config import ObservationConfig, SchedulerConfig, TimingTaskConfig, make_config
from .generator import TrialGenerator
from .monitor import Monitor, MonitorList
from .scheduler import DelayScheduler

__all__ = ["ActorCritic", "RLTrainer", "rollout", "attach_states", "summarise",
           "summarise_by_delay", "format_delay_report"]

WAIT, LICK = 0, 1


class ActorCritic(nn.Module):
    """A recurrent core with a linear policy head and a linear value head.

    ``core`` is any model from :mod:`timingtask.models`. Its ``step`` remains
    a pure function of ``(x, h)``.
    """

    def __init__(self, core: nn.Module, hidden_size: Optional[int] = None,
                 n_actions: int = 2):
        super().__init__()
        self.core = core
        h = int(hidden_size or getattr(core, "hidden_size"))
        self.policy = nn.Linear(h, n_actions)
        self.value = nn.Linear(h, 1)
        with torch.no_grad():
            # Start close to an indifferent policy.
            self.policy.weight.mul_(0.1)
            self.policy.bias.zero_()

    def init_state(self, batch_size: int, device=None) -> Tensor:
        return self.core.init_state(batch_size, device)

    def step(self, x: Tensor, h: Tensor):
        """One step. Returns ``(h, logits, value)``."""
        h = self.core.step(x, h)
        return h, self.policy(h), self.value(h).squeeze(-1)


def rollout(model: ActorCritic, gens: List[TrialGenerator], *,
            greedy: bool = False, max_steps: int = 4000, device: str = "cpu",
            min_action_prob: float = 0.0):
    """Run one episode (one trial) in each generator, in lockstep.

    The generators are batched for efficiency only; each keeps its own delay
    schedule, outcome history and trial history.

    ``min_action_prob`` mixes the policy with a uniform distribution before
    sampling, ``p <- eps + (1 - n_actions * eps) p``, which places a floor
    under every action probability. The mixed distribution is both the one
    sampled from and the one whose log-probability is scored.

    Returns a dict of ``(T, B, ...)`` tensors (``logp``, ``value``,
    ``reward``, ``entropy``, ``mask``, ``hidden``, ``logits``, ``obs``,
    ``iti``, ``post``), the initial state ``h_init`` and the list of trial
    ``records``.
    """
    B = len(gens)
    eps = float(min_action_prob)
    h = model.init_state(B, device)
    h_init = h
    obs = torch.tensor(np.stack([g.observe() for g in gens]), dtype=torch.float32,
                       device=device)
    done = np.zeros(B, bool)
    logps, values, rewards, ents, masks, hs, logits_all, itis, posts = \
        [], [], [], [], [], [], [], [], []
    obs_all = []
    records: List[Optional[Dict[str, Any]]] = [None] * B

    for _ in range(max_steps):
        obs_all.append(obs)
        h, logits, v = model.step(obs, h)
        if eps > 0:
            probs = torch.softmax(logits, dim=-1)
            n_act = probs.shape[-1]
            dist = Categorical(probs=eps + (1.0 - n_act * eps) * probs)
        else:
            dist = Categorical(logits=logits)
        a = logits.argmax(-1) if greedy else dist.sample()
        logps.append(dist.log_prob(a))
        ents.append(dist.entropy())
        values.append(v)
        hs.append(h)
        logits_all.append(logits)

        r = np.zeros(B, np.float32)
        nxt = np.zeros((B, gens[0].obs_size), np.float32)
        in_iti = np.zeros(B, np.float32)
        in_post = np.zeros(B, np.float32)
        for i, g in enumerate(gens):
            if done[i]:
                nxt[i] = obs[i].detach().cpu().numpy()
                continue
            in_iti[i] = float(g.phase == "iti")     # phase before the step
            in_post[i] = float(g.phase == "post")
            res = g.step(bool(a[i].item()))
            r[i], nxt[i] = res.reward, res.obs
            if res.record is not None:
                records[i] = res.record
                done[i] = True
        rewards.append(torch.tensor(r, device=device))
        itis.append(torch.tensor(in_iti, device=device))
        posts.append(torch.tensor(in_post, device=device))
        masks.append(torch.tensor(~done, dtype=torch.float32, device=device))
        obs = torch.tensor(nxt, dtype=torch.float32, device=device)
        if done.all():
            break

    # mask[t] is 1 while the trial was still running at step t
    m = torch.stack([torch.ones_like(masks[0])] + masks[:-1])
    return {"logp": torch.stack(logps), "value": torch.stack(values),
            "reward": torch.stack(rewards), "entropy": torch.stack(ents),
            "mask": m, "hidden": torch.stack(hs), "logits": torch.stack(logits_all),
            "h_init": h_init, "iti": torch.stack(itis),
            "obs": torch.stack(obs_all),
            "post": torch.stack(posts), "records": records}


def attach_states(out: Dict[str, Any]) -> None:
    """Attach per-step time series to each record in ``out["records"]``.

    Each series is truncated to the trial's own length:

        readout  (T,)      lick-minus-wait logit gap
        value    (T,)      value estimate
        hidden   (T, N)    hidden state
        obs      (T, n_in) observation vector
    """
    d = (out["logits"][..., LICK] - out["logits"][..., WAIT]).cpu().numpy()
    vv = out["value"].cpu().numpy()
    hh = out["hidden"].cpu().numpy()
    oo = out["obs"].cpu().numpy()
    for i, r in enumerate(out["records"]):
        if r is None:
            continue
        T = int(r["trial_steps"])
        r["readout"] = d[:T, i].astype(np.float32)
        r["value"] = vv[:T, i].astype(np.float32)
        r["hidden"] = hh[:T, i].astype(np.float32)
        r["obs"] = oo[:T, i].astype(np.float32)


class RLTrainer:
    """REINFORCE with a learned value baseline over parallel environments.

    Parameters
    ----------
    n_envs : number of parallel trial generators; one trial each per update.
    lr : Adam learning rate.
    gamma : return discount across steps within a trial.
    value_coef : weight of the value-regression loss.
    grad_clip : gradient-norm clip (0 disables clipping).
    reward_scale : global multiplier on environment rewards.
    iti_readout_penalty : shaped reward term that charges the lick probability
        at every ITI step.
    activity_penalty : loss term, coefficient on the mean squared hidden
        activity.
    activity_deriv_penalty : loss term, coefficient on the mean squared
        one-step change in hidden activity.
    activity_scope : ``"iti"`` averages the activity terms over ITI steps
        only; ``"full"`` over every live step.
    min_action_prob : floor under every action probability; see
        :func:`rollout`.
    """

    def __init__(self,
                 task_config: Optional[TimingTaskConfig] = None,
                 scheduler_config: Optional[SchedulerConfig] = None,
                 obs_config: Optional[ObservationConfig] = None,
                 *,
                 variant: Optional[str] = None,
                 n_envs: int = 16,
                 lr: float = 4e-3,
                 gamma: float = 1.0,
                 value_coef: float = 0.5,
                 grad_clip: float = 1.0,
                 reward_scale: float = 0.1,
                 iti_readout_penalty: float = 0.0,
                 activity_penalty: float = 0.0,
                 activity_deriv_penalty: float = 0.0,
                 activity_scope: str = "iti",
                 min_action_prob: float = 0.0,
                 seed: int = 0):
        if variant is not None:
            task_config, scheduler_config = make_config(variant)
        self.cfg = task_config or TimingTaskConfig()
        self.scheduler_cfg = scheduler_config or SchedulerConfig()
        self.obs_cfg = obs_config or ObservationConfig()
        self.n_envs = int(n_envs)
        self.lr, self.gamma = float(lr), float(gamma)
        self.value_coef = float(value_coef)
        self.grad_clip = float(grad_clip)
        self.reward_scale = float(reward_scale)
        self.iti_readout_penalty = float(iti_readout_penalty)
        self.activity_penalty = float(activity_penalty)
        self.activity_deriv_penalty = float(activity_deriv_penalty)
        if activity_scope not in ("iti", "full"):
            raise ValueError(f"activity_scope must be 'iti' or 'full', "
                             f"got {activity_scope!r}")
        self.activity_scope = str(activity_scope)
        self.min_action_prob = float(min_action_prob)

        rngs = [np.random.default_rng(seed * 1000 + i) for i in range(self.n_envs)]
        self.gens = [TrialGenerator(self.cfg,
                                    DelayScheduler(self.scheduler_cfg, r),
                                    self.obs_cfg, r) for r in rngs]

    @property
    def obs_size(self) -> int:
        return self.gens[0].obs_size

    def _returns(self, reward: Tensor, mask: Tensor) -> Tensor:
        T, B = reward.shape
        out = torch.zeros_like(reward)
        run = torch.zeros(B, device=reward.device)
        for t in range(T - 1, -1, -1):
            run = reward[t] + self.gamma * run * mask[t]
            out[t] = run
        return out

    def train(self, model: ActorCritic, *, steps: int = 2000,
              log_every: int = 100, monitors: Optional[Monitor] = None,
              on_log: Optional[Callable[[int, Dict], None]] = None,
              keep_records: bool = True,
              target_delay: Optional[float] = None,
              patience: Optional[int] = None, min_delta: float = 0.01,
              sched: Optional[Dict[str, Any]] = None,
              phase: str = "curriculum", reset: bool = True,
              score: str = "delay+correct",
              verbose: bool = True) -> Dict[str, List[float]]:
        """Train for up to ``steps`` updates. Returns a history dict.

        Every trial record is kept in ``self.records`` when ``keep_records``
        is True.

        Early stopping
            ``target_delay`` stops once the batch-mean required delay reaches
            the given value. ``patience`` stops after that many log points
            without an improvement greater than ``min_delta`` in the score,
            which is the batch-mean delay plus the rewarded fraction
            (``score="delay+correct"``) or the rewarded fraction alone
            (``score="correct"``).

        Training in stages
            ``sched`` applies scheduler-config overrides for this call and
            restarts every generator's current trial. ``reset=False`` keeps
            the records, weight snapshots and optimiser state from a previous
            call, so one agent can be trained through a sequence of delay
            schedules. Each record carries ``phase``.
        """
        if sched:
            for k, v in sched.items():
                setattr(self.scheduler_cfg, k, v)
            for g in self.gens:
                g.scheduler.reset()
                g._start_trial()
        if reset or not hasattr(self, "records"):
            self.records: List[Dict[str, Any]] = []
            self.weight_snapshots: List[Dict[str, Any]] = []
            self.opt = torch.optim.Adam(model.parameters(), lr=self.lr)
        mons = monitors if isinstance(monitors, MonitorList) else \
            MonitorList([monitors] if monitors is not None else [])
        opt = self.opt
        prev = {n: p.detach().clone() for n, p in model.named_parameters()}
        hist: Dict[str, List[float]] = {
            "step": [], "return": [], "p_engaged": [], "p_correct": [],
            "p_early": [], "entropy": [], "policy_loss": [], "value_loss": []}

        best_score, stale, self.stop_reason = -float("inf"), 0, "steps"
        for i in range(1, steps + 1):
            out = rollout(model, self.gens,
                          min_action_prob=self.min_action_prob)
            # m_data: the trial is still running (used for the return).
            # m: the trial is running and the action has a consequence, i.e.
            #    excluding the post-lick period (used for every loss term).
            m_data = out["mask"]
            m = m_data * (1.0 - out["post"])
            rew = out["reward"] * self.reward_scale
            if self.iti_readout_penalty:
                p_lick = torch.softmax(out["logits"], dim=-1)[..., LICK]
                rew = rew - self.iti_readout_penalty * p_lick.detach() * out["iti"]
            R = self._returns(rew, m_data)
            adv = (R - out["value"]).detach()
            # Advantage normalisation over loss-eligible steps.
            live = m.sum().clamp_min(1)
            mu = (adv * m).sum() / live
            sd = (((adv - mu) ** 2 * m).sum() / live).sqrt().clamp_min(1e-6)
            adv = (adv - mu) / sd

            policy_loss = -((out["logp"] * adv) * m).sum() / live
            value_loss = (((out["value"] - R) ** 2) * m).sum() / live
            # Entropy is logged, not optimised.
            entropy = (out["entropy"] * m).sum() / live
            loss = policy_loss + self.value_coef * value_loss

            act_pen = dact_pen = None
            if self.activity_penalty or self.activity_deriv_penalty:
                H_ = out["hidden"]                       # (T, B, N)
                w = m if self.activity_scope == "full" else m * out["iti"]
                n_w = w.sum().clamp_min(1)
                if self.activity_penalty:
                    act_pen = ((H_ ** 2).mean(-1) * w).sum() / n_w
                    loss = loss + self.activity_penalty * act_pen
                if self.activity_deriv_penalty:
                    h_prev = torch.cat([out["h_init"].unsqueeze(0), H_[:-1]], 0)
                    dact_pen = (((H_ - h_prev) ** 2).mean(-1) * w).sum() / n_w
                    loss = loss + self.activity_deriv_penalty * dact_pen

            opt.zero_grad()
            loss.backward()
            # clip_grad_norm_ returns the total norm before clipping.
            gnorm = float(nn.utils.clip_grad_norm_(
                model.parameters(),
                self.grad_clip if self.grad_clip else float("inf")))
            opt.step()

            recs = [r for r in out["records"] if r is not None]
            for r in recs:
                mons.on_trial(r)
            if keep_records:
                for _r in recs:
                    _r["phase"] = phase
                self.records.extend(recs)

            if i % log_every == 0 or i == 1:
                s = summarise(recs)
                hist["step"].append(i)
                hist["return"].append(
                    float((out["reward"] * m_data).sum() / len(self.gens)))
                with torch.no_grad():
                    pl = torch.softmax(out["logits"], -1)[..., LICK]
                    hist.setdefault("p_lick_iti", []).append(float(
                        (pl * out["iti"] * m).sum()
                        / (out["iti"] * m).sum().clamp_min(1)))
                for k in ("p_engaged", "p_correct", "p_early",
                          "p_iti_lick", "n_iti_licks", "p_cue_success",
                          "delay", "first_lick", "p_miss",
                          "value_gain", "reward_rate"):
                    hist.setdefault(k, []).append(s[k])
                hist["entropy"].append(float(entropy.detach()))
                if act_pen is not None:
                    hist.setdefault("act_pen", []).append(float(act_pen.detach()))
                if dact_pen is not None:
                    hist.setdefault("dact_pen", []).append(float(dact_pen.detach()))
                hist.setdefault("grad_norm", []).append(gnorm)
                with torch.no_grad():
                    W = model.policy.weight
                    w_delta = (W[LICK] - W[WAIT]).detach().clone()
                    w_v = model.value.weight[0].detach().clone()
                    hist.setdefault("w_delta_norm", []).append(float(w_delta.norm()))
                    hist.setdefault("w_value_norm", []).append(float(w_v.norm()))
                    hist.setdefault("W_rec_norm", []).append(
                        float(model.core.rec.weight.norm()))
                    hist.setdefault("W_in_norm", []).append(
                        float(model.core.inp.weight.norm()))
                    # Relative update size per parameter block, for blocks
                    # that receive a gradient. Series are kept the same
                    # length as ``step`` (NaN where undefined).
                    for n, p in model.named_parameters():
                        n0 = float(prev[n].norm())
                        if p.grad is not None:
                            hist.setdefault(f"d_{n}", []).append(
                                float((p.detach() - prev[n]).norm() / n0)
                                if n0 >= 1e-8 else float("nan"))
                        prev[n] = p.detach().clone()
                    self.weight_snapshots.append(
                        {"step": i, "w_delta": w_delta.cpu().numpy(),
                         "w_value": w_v.cpu().numpy(),
                         "b_delta": float(model.policy.bias[LICK]
                                          - model.policy.bias[WAIT])})
                hist.setdefault("trials", []).append(len(self.records))
                hist["policy_loss"].append(float(policy_loss.detach()))
                hist["value_loss"].append(float(value_loss.detach()))
                if verbose:
                    print(f"    {i:5d}/{steps}  return {hist['return'][-1]:8.2f}  "
                          f"engaged {s['p_engaged']:.2f}  correct {s['p_correct']:.2f}  "
                          f"early {s['p_early']:.2f}  H {float(entropy.detach()):.3f}  "
                          f"delay {s['delay']:.2f}", flush=True)
                if on_log:
                    on_log(i, {**s, "entropy": float(entropy.detach()),
                               "return": hist["return"][-1]})

                # stopping rules, evaluated at log points
                mean_delay = float(np.nanmean([r["delay"] for r in recs])
                                   if recs else float("nan"))
                if target_delay is not None and mean_delay >= target_delay:
                    self.stop_reason = f"target_delay {target_delay:g} reached"
                    break
                if patience:
                    sc = (s["p_correct"] if score == "correct"
                          else mean_delay + s["p_correct"])
                    if sc > best_score + min_delta:
                        best_score, stale = sc, 0
                    else:
                        stale += 1
                        if stale >= patience:
                            self.stop_reason = (
                                f"stalled: no gain > {min_delta:g} in "
                                f"{patience} log points")
                            break
        mons.close()
        if verbose or self.stop_reason != "steps":
            print(f"    stopped at update {i}/{steps}: {self.stop_reason}",
                  flush=True)
        return hist

    def evaluate(self, model: ActorCritic, *, n_trials: int = 400,
                 greedy: bool = False, freeze_scheduler: bool = True,
                 max_steps: int = 4000, collect_states: bool = False
                 ) -> List[Dict[str, Any]]:
        """Run the model without learning and return trial records.

        ``freeze_scheduler`` holds the required delay at its current value.
        ``greedy`` takes the most probable action instead of sampling.
        ``collect_states`` attaches per-step time series to each record (see
        :func:`attach_states`).
        """
        was_training = model.training
        model.eval()                     # also disables the recurrent noise
        if freeze_scheduler:
            for g in self.gens:
                g.scheduler.frozen = True
        recs: List[Dict[str, Any]] = []
        try:
            with torch.no_grad():
                while len(recs) < n_trials:
                    out = rollout(model, self.gens, greedy=greedy,
                                  max_steps=max_steps,
                                  min_action_prob=self.min_action_prob)
                    batch = [r for r in out["records"] if r is not None]
                    if collect_states:
                        attach_states(out)
                    recs += batch
        finally:
            if freeze_scheduler:
                for g in self.gens:
                    g.scheduler.frozen = False
            model.train(was_training)
        return recs[:n_trials]

    def _sched_snapshot(self):
        """Mutable scheduler state per environment, excluding the shared
        config and the RNG."""
        import copy
        return [{k: copy.deepcopy(v) for k, v in g.scheduler.__dict__.items()
                 if k not in ("config", "rng")} for g in self.gens]

    def _sched_restore(self, snaps):
        for g, s in zip(self.gens, snaps):
            g.scheduler.__dict__.update(s)

    def test(self, model: ActorCritic, *, n_trials: int = 10000,
             sched: Optional[Dict[str, Any]] = None,
             collect_states: bool = False, max_steps: int = 4000
             ) -> List[Dict[str, Any]]:
        """Run the model with frozen weights under a different delay
        schedule, then restore the original schedule.

        ``sched`` is a dict of :class:`~timingtask.config.SchedulerConfig`
        overrides, for example ``dict(mode="fixed", fixed_delay=1.0)``.
        """
        was_training = model.training
        model.eval()
        snaps = self._sched_snapshot()
        cfg_backup = {k: getattr(self.scheduler_cfg, k) for k in (sched or {})}
        recs: List[Dict[str, Any]] = []
        try:
            for k, v in (sched or {}).items():
                setattr(self.scheduler_cfg, k, v)
            for g in self.gens:
                g.scheduler.reset()
                g._start_trial()        # the current trial read the old delay
            with torch.no_grad():
                while len(recs) < n_trials:
                    out = rollout(model, self.gens, max_steps=max_steps,
                                  min_action_prob=self.min_action_prob)
                    if collect_states:
                        attach_states(out)
                    recs += [r for r in out["records"] if r is not None]
        finally:
            for k, v in cfg_backup.items():
                setattr(self.scheduler_cfg, k, v)
            self._sched_restore(snaps)
            model.train(was_training)
        return recs[:n_trials]

    def probe(self, model: ActorCritic, *, n_trials: int = 2000,
              max_delay: float = 1.8, collect_states: bool = False,
              promote: bool = True, sched: Optional[Dict[str, Any]] = None,
              max_steps: int = 4000) -> List[Dict[str, Any]]:
        """Run the model with frozen weights while the delay curriculum
        continues to advance, up to ``max_delay``.

        ``sched`` optionally replaces the live schedule for the duration of
        the probe (for example to restore a growing curriculum after staged
        training). With ``promote=True`` an environment still in the
        cue-association stage is advanced to delay training. All scheduler
        state is restored afterwards.
        """
        was_training = model.training
        model.eval()
        old_max = self.scheduler_cfg.max_delay
        self.scheduler_cfg.max_delay = float(max_delay)
        snaps = self._sched_snapshot() if sched else None
        cfg_backup = ({k: getattr(self.scheduler_cfg, k) for k in sched}
                      if sched else {})
        if sched:
            for k, v in sched.items():
                setattr(self.scheduler_cfg, k, v)
            for g in self.gens:
                g.scheduler.reset()
                g._start_trial()
        stages = [g.scheduler.training_stage for g in self.gens]
        if promote:
            for g in self.gens:
                if g.scheduler.training_stage == "cue_association":
                    g.scheduler.training_stage = "autolearn"
        recs: List[Dict[str, Any]] = []
        try:
            with torch.no_grad():
                while len(recs) < n_trials:
                    out = rollout(model, self.gens, max_steps=max_steps,
                                  min_action_prob=self.min_action_prob)
                    if collect_states:
                        attach_states(out)
                    recs += [r for r in out["records"] if r is not None]
        finally:
            self.scheduler_cfg.max_delay = old_max
            for k, v in cfg_backup.items():
                setattr(self.scheduler_cfg, k, v)
            if snaps is not None:
                self._sched_restore(snaps)
            else:
                for g, st in zip(self.gens, stages):
                    g.scheduler.training_stage = st
            model.train(was_training)
        return recs[:n_trials]


# --------------------------------------------------------------------------- #
# Behavioural summaries
# --------------------------------------------------------------------------- #
def summarise_by_delay(records: List[Dict[str, Any]], *,
                       max_rows: int = 8) -> Dict[str, Any]:
    """Split trials by required delay and report first-lick statistics.

    Because a trial ends at ``delay + answer_window``, longer delays admit
    later licks, so the raw mean first-lick time is not comparable across
    delays. ``first_lick_cut`` averages only licks earlier than ``cut``, the
    deadline of the shortest trial in the set. ``tracking`` is the slope of
    ``first_lick_cut`` against the delay: 1 indicates the lick time follows
    the delay, 0 a fixed interval.

    Delays are binned into at most ``max_rows`` groups when more distinct
    values are present.
    """
    cued = [r for r in records if not r.get("no_cue_trial")]
    if not cued:
        return dict(cut=float("nan"), rows=[], tracking=float("nan"))
    cut = min(float(r["delay"]) + float(r.get("answer_window", 0.0))
              for r in cued)
    delays = sorted({round(float(r["delay"]), 2) for r in cued})
    width = 0.0
    if len(delays) > max_rows:
        width = (delays[-1] - delays[0]) / max_rows or 0.1
    groups: Dict[float, list] = {}
    for r in cued:
        d = float(r["delay"])
        key = (round(delays[0] + width * int((d - delays[0]) / width), 2)
               if width else round(d, 2))
        groups.setdefault(key, []).append(r)
    rows = []
    for d in sorted(groups):
        g = groups[d]
        fl = np.array([r["first_lick_s"] for r in g
                       if r.get("first_lick_s") is not None], float)
        sub = fl[fl < cut]
        rows.append(dict(
            delay=d, n=len(g), p_lick=len(fl) / len(g),
            first_lick=float(fl.mean()) if len(fl) else float("nan"),
            first_lick_cut=float(sub.mean()) if len(sub) else float("nan"),
            n_cut=int(len(sub)),
            p_correct=float(np.mean([bool(r.get("rewarded")) for r in g])),
            p_early=float(np.mean([bool(r.get("early")) for r in g]))))
    tracking = float("nan")
    good = [r for r in rows if r["n_cut"] >= 20]
    if len(good) > 1:
        x = np.array([r["delay"] for r in good], float)
        y = np.array([r["first_lick_cut"] for r in good], float)
        if x.std() > 0:
            tracking = float(np.polyfit(x, y, 1)[0])
    return dict(cut=cut, rows=rows, tracking=tracking, binned=bool(width))


def format_delay_report(rep: Dict[str, Any], label: str = "",
                        indent: str = "    ") -> str:
    """Format the output of :func:`summarise_by_delay` as a text table."""
    if not rep["rows"]:
        return f"{indent}{label}: no cued trials"
    L = [f"{indent}{label} by delay "
         f"(first lick capped at {rep['cut']:.2f}s, the shortest trial's "
         f"deadline"
         + ("; delays binned)" if rep.get("binned") else ")"),
         f"{indent}  {'delay':>6s} {'n':>6s} {'p(lick)':>8s} {'FL':>7s} "
         f"{'FL_cut':>7s} {'n_cut':>6s} {'corr':>6s} {'early':>6s}"]
    for r in rep["rows"]:
        L.append(f"{indent}  {r['delay']:6.2f} {r['n']:6d} {r['p_lick']:8.2f} "
                 f"{r['first_lick']:7.3f} {r['first_lick_cut']:7.3f} "
                 f"{r['n_cut']:6d} {r['p_correct']:6.2f} {r['p_early']:6.2f}")
    L.append(f"{indent}  tracking slope d(FL_cut)/d(delay) = "
             f"{rep['tracking']:+.3f}   (1 = follows the delay, 0 = fixed "
             f"interval)")
    return "\n".join(L)


def summarise(records: List[Dict[str, Any]]) -> Dict[str, float]:
    """Behavioural summary of a set of trial records.

    ``p_engaged`` and ``p_correct`` are reported separately: a policy that
    never licks makes no errors, so a single accuracy figure cannot
    distinguish accurate timing from inaction.
    """
    cued = [r for r in records if not r.get("no_cue_trial")]
    if not cued:
        return dict(p_engaged=0., p_correct=0., p_early=0., p_miss=0.,
                    p_iti_lick=float("nan"), n_iti_licks=float("nan"),
                    p_cue_success=float("nan"),
                    delay=float("nan"), value_gain=float("nan"),
                    reward_rate=float("nan"),
                    first_lick=float("nan"), n=0)
    licked = [r for r in cued if r.get("decisive_lick_s") is not None]
    rew = [r for r in cued if r.get("rewarded")]
    fl = [r["first_lick_s"] for r in cued if r.get("first_lick_s") is not None]
    return dict(
        p_engaged=len(licked) / len(cued),
        p_correct=len(rew) / max(len(licked), 1),
        p_early=sum(bool(r.get("early")) for r in cued) / len(cued),
        p_miss=sum(bool(r.get("miss")) for r in cued) / len(cued),
        # ITI licking is computed over all trials, including catch trials,
        # since the stop-licking period is identical on both.
        p_iti_lick=sum(bool(r.get("iti_licked")) for r in records) / len(records),
        n_iti_licks=float(np.mean([r.get("n_iti_licks", 0) for r in records])),
        # Matches the scheduler's definition: an early lick does not count as
        # a cue response.
        p_cue_success=(sum(bool(r.get("cue_success")) and not r.get("early")
                           for r in cued) / len(cued)),
        delay=float(np.mean([r["delay"] for r in cued])),
        value_gain=float(np.mean([r.get("value_gain", 1.0) for r in cued])),
        reward_rate=float(np.mean([r.get("reward_rate", float("nan"))
                                   for r in cued])),
        first_lick=float(np.mean(fl)) if fl else float("nan"),
        n=len(cued))
